# Bayesian Linear Regression

In [1]:
import numpy as np

In [2]:
# It is assumed that there is a linear regression model for the features x1, x2, x3, x4 and y:
# y=a*x1+b*x2+c*x3+d*x4
a = -0.1
b = 0.2
c = 0.1
d = -0.1
# number of coefficients is M
M = 4

# the number of data samples
N = 100

# the random generator is created
rng = np.random.default_rng(seed=234623)
# feature values are determined
x1 = rng.uniform(low=1.0, high=5.0, size=N)
x2 = rng.uniform(low=-10.0, high=-1.0, size=N)
x3 = rng.uniform(low=2.0, high=10.0, size=N)
x4 = rng.uniform(low=-3.0, high=3.0, size=N)
# target values are determined
y = a*x1+b*x2+c*x3+d*x4

sigma = np.min(np.abs(y)) / 10.0
print('standard deviation of the data samples is as follows:')
print(sigma)

sigma_w = 0.01
print('standard deviation of the w coefficients is as follows:')
print(sigma_w)

# data matrix is created
X = np.zeros((N, 4))
# first column of X is the x1 feature
X[:, 0] = x1
# second column of X is the x2 feature
X[:, 1] = x2
# third column of X is the x3 feature
X[:, 2] = x3
# fourth column of X is the x4 feature
X[:, 3] = x4

standard deviation of the data samples is as follows:
0.0008805795608844613
standard deviation of the w coefficients is as follows:
0.01


In [3]:
# the coefficients are stored in the vector w as w=[a b c d]. The posterior distribution for w is to be computed.
# the covariance of the posterior distribution is computed as follows:
post_w_cov = np.linalg.pinv((1/(sigma_w*sigma_w))*np.identity(M)+(1/(sigma*sigma))*np.matmul(X.T, X))
print('The covariance of the posterior distribution for w is as follows:')
print(post_w_cov)
# the mean of the posterior distribution is computed as follows:
post_w_mu = np.matmul(post_w_cov, (1/(sigma*sigma))*(np.sum(np.repeat(np.expand_dims(y, axis=1), 4, axis=1)*X, axis=0)))
print('The mean of the posterior distribution for w is as follows:')
print(post_w_mu)

# let the posterior distribution for w be defined and sampled
rng = np.random.default_rng(seed=68549042)
sampled_w = rng.multivariate_normal(post_w_mu, post_w_cov, 10)
# Samples are drawn from the posterior distribution of w.
print('Samples of w coefficients drawn from the posterior distribution of w:')
print(sampled_w)

The covariance of the posterior distribution for w is as follows:
[[ 3.70376235e-09  7.58477697e-10 -9.51713698e-10 -1.06119081e-10]
 [ 7.58477697e-10  1.00617902e-09  4.88574546e-10  1.18509373e-10]
 [-9.51713698e-10  4.88574546e-10  9.86366858e-10  1.75722531e-10]
 [-1.06119081e-10  1.18509373e-10  1.75722531e-10  2.37320429e-09]]
The mean of the posterior distribution for w is as follows:
[-0.09999697  0.19999838  0.09999726 -0.09999815]
Samples of w coefficients drawn from the posterior distribution of w:
[[-0.09997087  0.20002779  0.10001318 -0.10007486]
 [-0.09997919  0.19993941  0.09993512 -0.10001798]
 [-0.09996986  0.19999073  0.09999584 -0.09993252]
 [-0.10004568  0.20003329  0.10004599 -0.09997012]
 [-0.10000711  0.19999814  0.09999558 -0.10002361]
 [-0.09991258  0.20000482  0.09997321 -0.09999694]
 [-0.09996745  0.19999297  0.09998651 -0.09996807]
 [-0.09995029  0.20003438  0.09999759 -0.10009381]
 [-0.10006042  0.19996777  0.10000886 -0.0999784 ]
 [-0.10000405  0.20001101 

The mean of the posterior for w vector is very close to the actual value. The samples from the posterior distribution are also very close to the original w vector.

In [4]:
# the test target value is created
# the random generator is created
rng = np.random.default_rng(seed=43857324)
# feature values are determined
test_size = 1
x1 = rng.uniform(low=-2.0, high=0.0, size=test_size)
x2 = rng.uniform(low=1.0, high=10.0, size=test_size)
x3 = rng.uniform(low=12.0, high=20.0, size=test_size)
x4 = rng.uniform(low=-6.0, high=-4.0, size=test_size)
x = np.array([x1, x2, x3, x4])
# target value is determined
y = a*x[0]+b*x[1]+c*x[2]+d*x[3]
print('The test target values are as follows:')
print(y)
# the posterior predictive distribution for the target variable y is computed.
# the variance of the posterior predictive distribution is sigma
# the mean of the posterior predictive distribution is computed
# mu_post_pred_dist = np.matmul(post_w_mu, x)+(1/(4*sigma*sigma))*np.matmul(np.expand_dims(x, axis=1).T, np.matmul(post_w_cov, np.expand_dims(x, axis=1)))
mu_post_pred_dist = np.matmul(post_w_mu, x)
print('The mean of the posterior predictive distribution is as follows:')
print(mu_post_pred_dist)
var_post_pred_dist = np.matmul(x.T, np.matmul(post_w_cov, x))
print('The variance of the posterior predictive distribution is as follows:')
print(var_post_pred_dist)

The test target values are as follows:
[2.83728451]
The mean of the posterior predictive distribution is as follows:
[2.83722801]
The variance of the posterior predictive distribution is as follows:
[[3.16419232e-07]]


The mean of the posterior predictive distribution is very close to the actual value. The variance of the posterior predictive distribution is also very small. 

# References